/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_didichuxing_diia_media_tools_MediaTools */

#ifndef _Included_com_didichuxing_diia_media_tools_MediaTools
#define _Included_com_didichuxing_diia_media_tools_MediaTools
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_didichuxing_diia_media_tools_MediaTools
 * Method:    run
 * Signature: ([Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_didichuxing_diia_media_tools_MediaTools_run
  (JNIEnv *, jclass, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
