/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_huolient_star_commen_ffmpeg_FFmpegHelper */

#ifndef _Included_com_huolient_star_commen_ffmpeg_FFmpegHelper
#define _Included_com_huolient_star_commen_ffmpeg_FFmpegHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_huolient_star_commen_ffmpeg_FFmpegHelper
 * Method:    run
 * Signature: ([Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_huolient_star_commen_ffmpeg_FFmpegHelper_run
  (JNIEnv *, jclass, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
